### ISSUE TITLE
Issue with import statement

### ISSUE THREAD

**Issue by iamsikun** [dipeshtech/ms_tweets#1]
Import statement returns 0 tweets and as a result, no JSON files are saved. I tried the answer from https://github.com/taspinar/twitterscraper/issues/296#issuecomment-637637929, and it successfully downloads the tweets. However, with the same begin/end dates and limits, the ms_tweets.json file I get is of a different size (18.6 MB) compared with yours.

**Comment by dipeshtech** [comment]
I have tested this around evening of 2020-03-26, which is a past date now. The extra difference can be attributed to those additional tweets which occurred after this commit. Purpose was just to show an example call.

**Comment by iamsikun** [comment]
Understand, thanks!
